### ISSUE TITLE
segfault with PyChess-style crazyhouse FEN

### ISSUE THREAD

**Issue by isaacl** [ddugovic/Stockfish#152]
```
setoption name UCI_Variant value crazyhouse
position fen r2q1rk1/pp2bb1p/2pp2pK/7N/3pPR1P/1B1P2p1/PPPq4/R7/PPBNNN b - - 49 25
```

seg fault. Would be great if these were more compatible, either by lichess outputting the SF version, or by SF parsing the lichess version.

lichess [converts](https://github.com/ornicar/lila/blob/21a8b0cd4f4fae531776dcb74041abefc2120131/ui/analyse/src/ceval/stockfishProtocol.js#L15-L19) FENs automatically for SF communcation, but this incompatibility makes it harder to test stockfish when copying a position from lichess.

**Comment by ddugovic** [comment]
GUI designer @HGMuller offers a [cogent explanation](http://github.com/ddugovic/Stockfish/issues/147#issuecomment-264669781) as does official-stockfish/Stockfish#905.

[Scott Meyers](http://youtube.com/watch?v=48kP_Ssg2eY) and [Randall Munroe](http://xkcd.com/927/) state it is essential that for any long-living standard everyone agree on the standard and that it be well-considered.  Other crazyhouse engines and GUIs already use [] syntax for pieces in hand because / syntax is ambiguous with FEN used in other variants to denote larger board dimensions; and while Lichess doesn't yet have variants with larger board dimensions maybe one day they might as well!

Looking forward, it would be great if Lichess and HGM could have a conversation about this so engine developers are not "caught in the crossfire" (to use a metaphor).

**Comment by ornicar** [comment]
Hi,

It's not "lichess style". It comes from scidb.

When implementing crazyhouse on lichess, one year ago, I looked for a standard and all I found was this: http://scidb.sourceforge.net/help/en/FEN.html

And so I followed it.

Now there's millions of these crazyhouse FENs in lichess database.

But if stockfish goes for another notation, I'll find a way to support it as well.

**Comment by ddugovic** [comment]
Thanks for the clarification and I apologize that I mis-attributed that FEN style.  I'll carefully reflect on this and after sunrise research the current state of affairs w/respect to GUIs, ICSs, engines, databases, etc.

**Comment by ddugovic** [comment]
Not counting recent development...
WinBoard style []:
* Imortal 2.0
* TJChess 1.1
* Sjaak II 1.3.0

WinBoard style [] and PyChess(SCIDB) style /:
* Sunsetter
* Sjeng

**Comment by HGMuller** [comment]
I can add:

WinBoard style []:

  * CrazyWa 0.1.2
  * NebiyuAlien 1.45

BTW, WinBoard on reading understands both the [] and / style. It would 
always write the position in [] style (to engine or PGN file or 
clipboard), though no matter in which format it was originally read.


Op 12/4/2016 om 4:36 PM schreef Daniel Dugovic:
