### ISSUE TITLE
value of multiple copies of a piece in hand?

### ISSUE THREAD

**Issue by isaacl** [ddugovic/Stockfish#265]
I notice that stockfish will happily grab a pawn when it already has 5 in hand, which isn't usually productive.

I wonder if it might be worth assigning a lower in hand value for pawns above a certain threshold.

**Comment by ddugovic** [comment]
I once tried introducing quadratic bonuses (in material.cpp) based on having a variety of bonuses in hand or based on the total piece count in hand, and my implementation didn't seem to have any effect.

**Comment by ianfab** [comment]
@ddugovic I believe that your idea should work, but last time you started the [tuning session](http://35.161.250.236:6543/tests/view/5896fe226e23db014ac09fa3) from non-zero values with small ranges, so they did not change much. I think that starting tuning from a version that is functionally equivalent to master (quadratic in-hand bonuses equal to zero) and using wide ranges (sth. like [-1000, 1000], since they are divided by 16) should help to find parameter values that outperform master.

**Comment by ddugovic** [comment]
@ianfab I have created a new [tuning session](http://35.161.250.236:6543/tests/view/58b8024c6e23db7956a14269).  Please let me know if I have overlooked anything else...

**Comment by ianfab** [comment]
@ddugovic The default parameter range is [0, 2 * v] if the starting value is v, so you have to explicitly set the range if you start from zero using `SetRange`, i.e. [`TUNE(SetRange(-1000, 1000), QuadraticOursInHand, QuadraticTheirsInHand);`](https://github.com/ddugovic/Stockfish/commit/ef67f94c5cd7350daa4aac5509b4772e47778159#diff-c74eb33120f9e932f7cfc0be07fa91d2R302), otherwise the parameters can not be tuned as far as I know.

**Comment by ddugovic** [comment]
Thanks, that makes sense & points out a flaw in my parameter values (using c=23.6 rather than c=236).  I have created a new [tuning session](http://35.161.250.236:6543/tests/view/58b808b26e23db7956a1426d).

**Comment by ianfab** [comment]
The patch with tuned quadratic bonuses passed STC: http://35.161.250.236:6543/tests/view/58bbe2c06e23db7956a14291

**Comment by isaacl** [comment]
Your patch has names like QuadraticInHand, but that seems more for covariant terms of piece synergy.

That's definitely a great concept and potentially useful, but my original idea was about the decreasing usefulness of tons of pieces in hand, especially tons of pawns.

**Comment by ianfab** [comment]
@isaacl The diagonal elements in `QuadraticOursInHand` account for that. E.g. the element [1][1] of the array corresponds to the evaluation term `-27 * number_of_pawns^2 / 16`, which means that the piece value of the nth pawn in hand is decreased by `-27 * (2n - 1) / 16`. So I think that his patch is a generalization of your idea.

**Comment by ddugovic** [comment]
Glad to see it passed STC!  I have created an LTC test.

Oops, can @isaacl or @ianfab confirm if my comment is incorrect?
https://github.com/ddugovic/Stockfish/commit/ef67f94c5cd7350daa4aac5509b4772e47778159#diff-c74eb33120f9e932f7cfc0be07fa91d2R297

**Comment by ianfab** [comment]
@ddugovic If you refer to the "our pieces" comment, I do not see anything wrong with since it refers to https://github.com/ddugovic/Stockfish/commit/ef67f94c5cd7350daa4aac5509b4772e47778159#diff-c74eb33120f9e932f7cfc0be07fa91d2R385.

**Comment by isaacl** [comment]
`pieceCount[Us][pt1] * v;` is the wrong extra factor for pieces in hand.  Instead, you need a loop where the new factors are added wtih `bonus += pieceCountInHand[Us][pt1] * v`

**Comment by ianfab** [comment]
You are right, I have not read the code carefully enough. I thought that the code was intended to do what I tried to explain. Since it does not, we might want to introduce and tune new arrays for that idea.

**Comment by ddugovic** [comment]
Maybe so... in any event, "covariant" is more accurate than quadratic.

Either way given [this condition](https://github.com/ddugovic/Stockfish/commit/ef67f94c5cd7350daa4aac5509b4772e47778159#diff-c74eb33120f9e932f7cfc0be07fa91d2L340) it seems likely to me that Isaac's suggestion (and a retune of the constants) could outperform this code although I'm unsure what sort of test parameters we'd want to use...

**Comment by isaacl** [comment]
Well, if it's possible to tune a covariant table I think that could be valuable.  It just has to allow true quadratic terms for pieces in hand, which requires a separate loop.

For example,  2 * knight + 1 pawn is often much more valuable than either ones on their own.  (in general, knight + diag is better than either only diags or only knights).

**Comment by isaacl** [comment]
Note also that you should really have a 3rd zh matrix, terms between our pieces in hand and our pieces on board.

I'd suggest adding that, but then we might be able to separately to reduce the number of terms since material on board basically doesn't change (besides promotion).

**Comment by isaacl** [comment]
Actually, how about adding an our drop x our board matrix and removing our drop x their drop matrix. 

4 cross terms is usually enough except when there's a promotion. In that case it's probably more better to keep personal synergy accurate. Otherwise dropping a piece on board will count as losing synergy.

**Comment by ianfab** [comment]
These different kinds of cross terms definitely contain some information, but I think we should try to have as few terms as possible, since there is much correlation between many terms, and it might be difficult to tune them.

What do you think about using the total piece count (on board+in hand) for `QuadraticOurs` and `QuadraticTheirs`, since this helps to evaluate general imbalances like queen for two minor pieces regardless of whether they are in hand or on the board. Then we could add `QuadraticOursInHand` as defined in #273 to take account of what you said about having tons of pawns in hand, etc. I think that this would be the most stable setup of higher-order terms, and we would only need one additional array (or two if we include `QuadraticTheirsInHand`).

**Comment by ddugovic** [comment]
@ianfab I think that is an excellent design with minimal added complexity and likely would defeat #273 in tests.  If we are all agreed upon this approach I suppose [this tuning](http://35.161.250.236:6543/tests/view/58c1486e6e23db7956a142db) and subsequent STC/LTC don't need to complete?

**Comment by ianfab** [comment]
The tuning results look reasonable to me, so I am not opposed to testing them, but if you are confident that my idea will perform well, I am also fine with trying it first. Either way, I won't be able to write any code before Sunday, so if you want to submit tuning sessions or tests for any of the approaches, please go ahead. (The regression tests in the queue have negative priority, so they will only be executed if the queue is otherwise empty.)

**Comment by ddugovic** [comment]
I think having #273 in place first might help us tune your idea (or test that it's well-tuned) so I'll submit an STC test.

**Comment by isaacl** [comment]
@ianfab's idea sounds good to me too.  I'd skip the QuadraticTheirsInHand array for now, just QuadOurs, QuadTheirs with total piece counts, and a QuadOursInHand for drop synergy.

**Comment by ddugovic** [comment]
Shoot, I thought I had [fixed this code](https://github.com/ddugovic/Stockfish/commit/ba34ec3f85afb33d1ccba0f13049e0e13d398382) before submitting it for testing.  Apologies for my confusion; may I resubmit it with the corrected code?

**Comment by ddugovic** [comment]
@isaacl My attempt to rewrite the bonus formula (to include in-hand pieces with on-board pieces) [failed](http://35.161.250.236:6543/tests/view/58e0e6906e23db2fa8080ef0).

**Comment by isaacl** [comment]
:-(  OK I'll send you a code patch adding the in hand pieces to board pieces. was waiting to see if your rewrite would work

**Comment by ddugovic** [comment]
Simply amazing, after re-tuning (atop latest master which has no ceiling for king danger) adding the pieces together passes STC in just 2480 games!  Onward to LTC!
http://35.161.250.236:6543/tests/view/58ef70a26e23db2fa8081051
http://35.161.250.236:6543/tests/view/58efeeb56e23db2fa8081054

**Comment by MichaelB7** [comment]
!!!!😊
