### ISSUE TITLE
Improve lone-king fortress detection

### ISSUE THREAD

**Issue by ddugovic** [ddugovic/Stockfish#320]
http://en.lichess.org/SXyu5Dj4/black#4
http://en.lichess.org/forum/lichess-feedback/bug-like-stockfish-behavior-insufficient-time-for-analysis#6

**Comment by ddugovic** [comment]
I have submitted a test which appears to improve Stockfish zugzwang detection:
http://35.161.250.236:6543/tests/view/58f255fe6e23db2fa8081081

**Comment by ianfab** [comment]
The problem with such changes is that many of these endgame functions are called extremely rarely, so the change in Elo probably is less than 1 Elo (and also heavily depending on adjudication conditions) and even in official fishtest it is unlikely that one is able to measure this. That is why there are almost no upstream changes to the endgame evaluation functions.

Testing changes to the endgame evaluation functions as simplifications does not work either, since almost any random change would pass due to the small change in Elo. So there would have to be an "opening" book with a very carefully hand-picked set of (close to) endgame positions in order to get a better Elo sensitivity. It is however very difficult to prove that a chosen set is representative and unbiased.

**Comment by ppigazzini** [comment]
@ianfab 👍 there was several propositions to measure endgame improvements in official fishtest, practical steps never followed, IIRC some specialized endgame code was eradicated.

The thread [Current status of endgame knowledge](https://groups.google.com/forum/?fromgroups=#!searchin/fishcooking/endgame$20book|sort:relevance/fishcooking/lR4uK_EUB5k/MOXA57ciDwkJ) is a mandatory reading :)

**Comment by ddugovic** [comment]
Thanks; this all makes sense & now I have read that thread.

Sorry for causing so much concern: my purpose in creating this issue was to demonstrate how infeasible it is to solve every problem reported by a user, yet error reports are taken seriously.
