### ISSUE TITLE
Losers variant en passant move validation

### ISSUE THREAD

**Issue by ddugovic** [ddugovic/Stockfish#341]
A pinned pawn may en passant as long as doing so does not break the pin.  This works in giveaway chess:

```
setoption name UCI_Variant value losers
position fen rnbqkbnr/ppp2ppp/3p4/4pP2/8/7K/PPPPP1PP/RNBQ1BNR w kq e6 0 2
perft 1
```

**Comment by ianfab** [comment]
I slightly modified the position and got another issue:
```
setoption name UCI_Variant value losers
position fen 1nbqkbnr/ppp2ppp/3p4/r3pP1K/8/8/PPPPP1PP/RNBQ1BNR w k e6 0 1
perft 1
```
does not return any move, even though there should be many legal moves. Your patch seems to fix the move generation for the first position, but unfortunately not for the second one. However, if we do not find a quick solution to fix both, I do not have any objections against your patch, since it fixes a bug and does not seem to break anything.

**Comment by ddugovic** [comment]
Ah, right... I'll see if I can fix that with `1nbqkbnr/1ppp1ppp/8/r3pP1K/p7/8/PPPPP1PP/RNBQ1BNR w k -` which can be reached.

**Comment by ianfab** [comment]
I have just noticed that you submitted the second fix with [0,10] bounds. I lowered priority and resubmitted it with [-10,5] bounds. Please let me know if that is ok.

**Comment by ddugovic** [comment]
That is OK, sorry for my mistake.
