### ISSUE TITLE
ZH : opperwezen stronger again : 6 wins ! (15+0 and 1+0)

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#380]
https://lichess.org/viRHaJOq
https://lichess.org/aEcWuW4h
https://lichess.org/h71C7U7I#37

https://lichess.org/5f4iK1wL#51
https://lichess.org/EZCK3E23#54
https://lichess.org/zwHZjZsc#73

Crazy guy ! :-)
May be there are a lot of opening preparation ...

**Comment by ppigazzini** [comment]
@Vinvin20 It would be useful if opperwezen (or other strong ZH players) could give his point of view about the weaknesses in SF's play

**Comment by ddugovic** [comment]
Simply unreal.  I'll ask around & see if the Lichess cluster is using the latest Stockfish...

**Comment by Vinvin20** [comment]
>Simply unreal. I'll ask around & see if the Lichess cluster is using the latest Stockfish...

That would explain the things :-)
Please let us know when you'll get the answer ...

**Comment by ianfab** [comment]
Considering opperwezen's playing strength, his score of something like 20% is not unexpected. Losing a game is not per se a bug, but some of the examples indeed look strange, since they are not reproducible.

**Comment by ddugovic** [comment]
> Considering opperwezen's playing strength, his score of something like 20% is not unexpected. Losing a game is not per se a bug, but some of the examples indeed look strange, since they are not reproducible.

Exactly; sorry for my lack of clarity but that is what I found stunning.  Today Lichess is upgrading Stockfish on its hosted machines.  Hopefully over time [fishnet](http://github.com/niklasf/fishnet) donors (machines not under Lichess control) will upgrade as well.

**Comment by ianfab** [comment]
Thanks a lot for the info.

I think that a dedicated team or thread in the lichess forum would be more suitable to share and discuss such findings.

**Comment by ddugovic** [comment]
I too think a dedicated team, Lichess forum thread, etc. would be appropriate.

I am an active member in:

* Lichess forums / teams / Q&A:
** Lichess Feedback http://lichess.org/forum/lichess-feedback
** Coders http://lichess.org/forum/team-coders
** Crazyhouse Engine Development and Game Analyses http://lichess.org/forum/team-crazyhouse-engine-development-and-game-analyses
** Q&A http://lichess.org/qa

and I respond to `@Toadofsky` in the Lichess forums

Additionally, I am an active member in the Lichess discord http://discord.gg/AWSze7n

I think any and/or all of the above are viable options for discussion of issues not reproducible in latest Stockfish.  In fact, I have already created such a thread, and apparently nobody other than myself is using it (perhaps due to its negative connotation -- that coding cannot fix all real-world problems, especially those which are ill-defined and/or nonreproducible):
http://lichess.org/forum/team-coders/stockfish-xy-problems

I suggest someone pick one of the above options.  Maybe I need to create a Lichess team devoted to tracking how/when Lichess deploys Stockfish updates?

**Comment by niklasf** [comment]
As an aside, I believe *all* playing instances of Stockfish have been updated. (Contributed instances are only used for analysis.)

**Comment by ddugovic** [comment]
Thanks, that is good news to hear.

I have created an AI level 8 tracker for people reporting "AI level 8 blundered but I don't know if this is reproducible in latest Stockfish":
http://lichess.org/forum/lichess-feedback/ai-level-8-tracker
