### ISSUE TITLE
Crazyhouse SF : mission accomplished vs humans

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#428]
After 2 recent improvements : http://35.161.250.236:6543/regression

I took a look back and I concluded that SF-ZH is now out of the reach for top humans : 
10 months ago, JannLee lost 4-0 in long games : https://www.youtube.com/watch?v=_J8yKv_Wzi4
and 38-1 in bullet : https://www.youtube.com/watch?v=nXKKPmunAtw

The engine has been improved a lot since this time.

Even on level 7, Stockfish beat Yasser Seirawan (top 3 player in ZH) 36-12 on the 2 last weeks : https://lichess.org/@/yasser-seirawan/search?dateMin=2w&dateMax=0d&perf=18&hasAi=1&aiLevelMin=7&sort.field=d&sort.order=desc

I searched for hours and hours for strange things in Stockfish play against humans. I'm done now !
Thanks to everyone for this amazing achievement !

**Comment by MichaelB7** [comment]
👍🤜will have to go grab the latest source and make a macOS version available - Nice work , appreciate it.

**Comment by ddugovic** [comment]
Thanks for testing @Vinvin20 !  It's clear that at rapid or faster time controls, defeating full-strength Stockfish 1-on-1 is extraordinarily challenging!  I wonder what other sorts of contests would make sense...

Also, it's been awhile since the [1st CCVA Computer Championships](https://sites.google.com/site/zhassociation/computers/tournaments/1st-ccva-computer-championships).  This winter I hope to [broadcast](http://lichess.org/broadcast/new) an exhibition SF - Sunsetter (or other engine) match.

**Comment by ianfab** [comment]
I am also satisfied with the performance in crazyhouse, although I think there still should be room for improvement as the evaluation still fluctuates quite a bit between moves. However, the mistakes now usually are small enough to not immediately lose the game (unlike the blunders of the versions a few of months ago), so human players often can not convert it into a win even if Stockfish "blunders".

Other variants, especially the more strategic ones like atomic, horde, and racing kings, are lagging behind crazyhouse quite a bit (not necessarily in terms of improvement, but in terms of playing strength relative to human players), so I will perhaps try to focus a bit more on them (besides S-Chess). For most variants other than crazyhouse there have not been many games between Stockfish and the strongest players of these variants, so it is also hard to estimate the playing strength.

**Comment by Vinvin20** [comment]
>there still should be room for improvement as the evaluation still fluctuates quite a bit between moves.

I think that's because in Crazyhouse, there's no (very) quiet position, the advantage can go from one side to the other side in a couple of moves. The capacity to put a piece wherever one want makes the game way more chaotic than chess.

**Comment by ianfab** [comment]
I went trough some high-level human games to find positions where there might be long mate combinations in order to test Stockfish's limits in mate finding, and collected the positions in a [lichess study](https://lichess.org/study/WYBVhqpr). Stockfish's results of course do not really prove the mate sequences, but they look good, so I assume that they are correct, although there might be shorter mates it was not able to find.

I was amazed that it found a mate in 17 in about one second, and was able to resolve a mate in 23 where the king starts on g8 and is mated on b8 after a walk via d5, although that took around 30 minutes to calculate. In the third position Stockfish announces a mate in 16 involving several non-checking moves after 10 minutes, but going through the PV it turned out that it did not find the best sequence for the winning side.

**Comment by ianfab** [comment]
> Also, it's been awhile since the 1st CCVA Computer Championships. This winter I hope to broadcast an exhibition SF - Sunsetter (or other engine) match.

@ddugovic Ferdinand Mosca [announced](http://www.talkchess.com/forum/viewtopic.php?t=65921) that there will be a second CCVA Championship at the end of the year. I suggest to use [fishnet-071017](https://github.com/niklasf/Stockfish/releases/tag/fishnet-071017) as I think it does not make much of a difference whether that version or a possible more recent version will be used.

**Comment by ddugovic** [comment]
@ianfab That sounds good to me (I agree SF is quite strong & it shouldn't make a large difference whether a possible more recent version is used).

**Comment by ddugovic** [comment]
2nd CCVA Championships results are now in:
http://www.talkchess.com/forum/viewtopic.php?p=745646#745646

Many thanks to Ferdinand, Fabian, Niklas, Vincent, and Thibault for making this achievement possible.
