### ISSUE TITLE
Slow refresh rate of framework 

### ISSUE THREAD

**Issue by Nordlandia** [ddugovic/Stockfish#438]
How often do the website update?

http://35.161.250.236:6543/tests

**Comment by ianfab** [comment]
@Nordlandia If you refer to inactive machines or the user stats, I have run the update scripts manually in the last weeks, and I was travelling over the weekend, so I did not have access to the server. I was doing it manually due to some issues that were fixed already some time ago, so I will perhaps switch to letting them run automatically again.

**Comment by Nordlandia** [comment]
Yeah i was referring to inactive machines or the user stats.
