### ISSUE TITLE
A ZH game with blunders from SF

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#490]
May be this game can help to improve SF-Zh.
Especially 21...d5?? because of 22.P@d7!!

https://lichess.org/uZo8Zbgb

**Comment by ddugovic** [comment]
Yeah, I'm trying to change `see_ge` of `position.cpp` which looks really complicated & confusing and doesn't account for sequences of captures involving promoted pieces.

**Comment by ianfab** [comment]
Since pawn drops on the 7th rank are very dangerous, I submitted a [test](http://35.161.250.236:6543/tests/view/5a53e1d76e23db35f28bb1a5) for a patch that handles pawn drops to the 7th rank as captures, the same way as it is done for promotions to queen. That might be a bit too much, but let's give it a try.

**Comment by ddugovic** [comment]
Hm, I wonder if changing the definition of `Position::capture_or_promotion(Move)` (consumed by `search.cpp`) to include such drops could similarly be useful.

**Comment by ianfab** [comment]
@ddugovic Yeah, that should be a less dramatic change then handling them as captures in move picking, but might achieve similar effects, so it sounds like a promising idea to me.

**Comment by ddugovic** [comment]
@ianfab OK, cool.  Here goes nothing!
http://35.161.250.236:6543/tests/view/5a53e8b36e23db35f28bb1aa

**Comment by Vinvin20** [comment]
3 more games with blunders from SF level 8 : 
https://lichess.org/KDH3s0im#45
https://lichess.org/gcwg4BT1/black#15
https://lichess.org/R4D1sDQN#40

**Comment by ianfab** [comment]
Some of the peaks in the analysis graph turn out to be caused by evaluation fluctuations, some are only slight mistakes after deeper analysis, and a few seem to be real blunders. However, I can not find a clear pattern in the mistakes apart from that Stockfish is maybe overplaying the positions instead of dropping pieces to strengthen its own camp.

[One blunder](https://lichess.org/R4D1sDQN#89) turned out to really completely switch the evaluation from around +15 to -15 (from black's perpective) when analyzing deeper. But even there I find it hard to identify a reason for the blunder.

Nevertheless, I find this position very interesting to analyze, since it is really fascinating to see how black can make progress despite white's king looking realatively safe. 45... P@h2! is the winning move. The idea seems to be that if the bishop takes, it is deflected from f2, so black can continue with Bxf2+ which further opens up the king position. If the king takes (Kh1 leads to mate), black can play N@d2 with tempo (!) (either directly or after an intermediate move P@h4), because Nxf1+ is actually a mate threat. So (although there are a lot of side lines) P@h2+ essentially gains a tempo at the cost of only one pawn, which seems negligible in such a position with many pieces in hand.

The only idea for improving Stockfish I got from these analyses is that one could give a bonus to moves that threaten to give check on the next move (with non-negative SEE), but I am not entirely sure how and where to do that (move ordering, LMR, ...?).

**Comment by ddugovic** [comment]
Likewise I tried many move-ordering and SEE ideas recently and none of them worked.

**Comment by ddugovic** [comment]
The last few upstream commits are quite interesting...
"Simplify verification search"
"Revert to old time management"
"Use mobility in kingsafety"

Are these SF blunders reproducible offline with latest `master`?

**Comment by ddugovic** [comment]
Welp... P@d7 is just very difficult to find in this particular position and (having attempted 9 different patches in addition to those attempted by Fabian) there appears not to be a generic solution to discovering pawn-on-7th-rank threats.

**Comment by Vinvin20** [comment]
Here, the key is probably : pawn on 7th is strong when the back-rank is weak and the player has a rook or a queen in hand.

**Comment by ddugovic** [comment]
@Vinvin20 I attempted to code a patch based on your idea, but it probably wasn't exactly what you had in mind: a3defd362c3265a7eec8ed4c605039df07df5ca9

Feel free to try coding a patch of your own too...

**Comment by ddugovic** [comment]
Thanks to simplification 5d57bb467a4d703f480c87f58687705e2f56e338 it's possible pawn-on-7th moves might be pruned less aggressively (or that some parameter tuning without changing logic might improve this).

**Comment by ddugovic** [comment]
With current `master` the move `21... Ng3` is quickly found to be winning; however, the following test fails to find `22. Qc6!` after 30 seconds:

```
setoption name UCI_Variant value crazyhouse
position fen r5k1/p4ppp/3pp3/6qn/3PB3/4P1B1/PrP2PPP/R4RK1/PBQPBnpnn b - - 41 21
go movetime 30000 searchmoves d6d5
```

**Comment by ddugovic** [comment]
Probably people should submit crazyhouse parameter-tweaking patches (possibly using SPSA to tune first) since those patches are easy (but tedious) to create and would address more than this one position.

**Comment by ianfab** [comment]
@ddugovic Could you please outline why 22. Q@c6 is a good move after 21...d5? I do not understand how it is winning and Stockfish can not not show me either, since it claims that Q@c6 is losing.

Well, I think finding those people is the issue, not finding suitable ways for them to contribute.

**Comment by ddugovic** [comment]
@ianfab My mistake, Stockfish does find `22. P@d7!` (not `Q@c6`).  I got confused re-reading the original issue after having some difficulty reproducing it.  Here is what I observed (when I force Stockfish to evaluate `22... d5??`):

```
info depth 19 seldepth 32 multipv 1 score cp 89 upperbound nodes 12231148 nps 558270 hashfull 999 tbhits 0 time 21909 pv d6d5 P@d7
info depth 19 seldepth 32 multipv 1 score cp 81 upperbound nodes 12247883 nps 558448 hashfull 999 tbhits 0 time 21932 pv d6d5 P@d7
info depth 19 seldepth 33 multipv 1 score cp 70 upperbound nodes 12648175 nps 560596 hashfull 999 tbhits 0 time 22562 pv d6d5 P@d7
info depth 19 seldepth 33 multipv 1 score cp 54 upperbound nodes 12797277 nps 561555 hashfull 999 tbhits 0 time 22789 pv d6d5 P@d7
info depth 19 seldepth 33 multipv 1 score cp 32 upperbound nodes 12900865 nps 562349 hashfull 999 tbhits 0 time 22941 pv d6d5 P@d7
info depth 19 seldepth 33 multipv 1 score cp 3 upperbound nodes 13061515 nps 562366 hashfull 999 tbhits 0 time 23226 pv d6d5 P@d7
info depth 19 seldepth 35 multipv 1 score cp -34 upperbound nodes 13366682 nps 560988 hashfull 999 tbhits 0 time 23827 pv d6d5 P@d7
info depth 19 seldepth 35 multipv 1 score cp -3 lowerbound nodes 13818295 nps 560579 hashfull 999 tbhits 0 time 24650 pv d6d5
info depth 19 seldepth 35 multipv 1 score cp -84 upperbound nodes 14032912 nps 559213 hashfull 999 tbhits 0 time 25094 pv d6d5 P@d7
info depth 19 seldepth 44 multipv 1 score cp -11 lowerbound nodes 14137678 nps 559642 hashfull 999 tbhits 0 time 25262 pv d6d5
info depth 19 seldepth 44 multipv 1 score cp 93 lowerbound nodes 15231245 nps 559560 hashfull 999 tbhits 0 time 27220 pv d6d5
info depth 19 seldepth 44 multipv 1 score cp 93 nodes 16799946 nps 559699 hashfull 999 tbhits 0 time 30016 pv d6d5
bestmove d6d5 ponder P@d7
```

**Comment by ianfab** [comment]
@ddugovic `22. P@d7` does not seem convincing either. It was of course not me who found this, but Stockfish quickly discovered the crushing `22. P@d7? N@h3! 23. Kh1 Qxg3!!`, and after some analysis I am quite convinced that it is right.

**Comment by ddugovic** [comment]
@ianfab Thanks, that makes sense.

It sounds as if possibly I've been "on a wild goose chase," but also the original issue(s) are no longer reproducible?

**Comment by ianfab** [comment]
@ddugovic Ah, I did not notice that P@d7 was the originally suggested "refutation". That SF incrementally finds refutations with increasing thinking time is a good sign, in contrast to being completely blind for certain moves like in the past. The position is very interesting since it seems like neither side has a forced mate (at least not in something like <15 moves), but still both sides have strong attacks with many (mate) threats. However, I do not see an obvious move SF misses in this position, so it might not help that much for getting concrete ideas for improvements.

**Comment by ddugovic** [comment]
@ianfab I agree.

Curiously 1171835ee7541404895940c812cf7e067766e184 increases `nps` by about 10% (analyzing the position after `22. P@d7 Nxg3 23. hxg3 B@f8` where `24. Bxh7+!` must be winning):

```
info depth 23 seldepth 39 multipv 1 score cp 697 lowerbound nodes 180811490 nps 506449 hashfull 999 tbhits 0 time 357018 pv e4h7
info depth 23 seldepth 39 multipv 1 score cp 719 lowerbound nodes 201287087 nps 504120 hashfull 999 tbhits 0 time 399284 pv e4h7
```

versus the earlier:

```
info depth 23 seldepth 45 multipv 1 score cp 707 lowerbound nodes 187430754 nps 481677 hashfull 999 tbhits 0 time 389121 pv e4h7
info depth 23 seldepth 45 multipv 1 score cp 648 nodes 191330622 nps 481320 hashfull 999 tbhits 0 time 397512 pv e4h7 g8h7 Q@h2 P@h6 P@f4 g5f5 N@g5 h7h8 B@h7 B@g6 B@d3 N@e2 d3e2 g6h7 P@c7 B@d8 c7d8q a8d8 g5h7 f8d6 N@e8 d8d7 e8d6 d7d6 B@a3 f5c2 a3d6 c2e2 R@c8 h8h7
```

**Comment by ianfab** [comment]
@ddugovic I do not think that the change in nps has any obvious meaning here. Looking at the code it can not be a (significant) speed-up, so I guess it might simply be related to a different number of TT hits in the two searches.

Note: Your commit introduces a a lichess-style crazyhouse FEN into the benchmark set. I am not sure whether that was intentional, but it might anyway be useful to avoid breaking support for that in the future.

**Comment by ddugovic** [comment]
Thanks @ianfab and I agree, it seems the change is not a (significant) speed-up for most positions in general (or it might be, at loss of Elo) so the nps change is not meaningful here.

That formatting was unintentional & I'll change it; for simplicity's sake (in case in the future GUIs/interfaces fully adopt the "pocket" style and on a major release we can finally drop support for the "ninth rank" style) I prefer to have all crazyhouse FENs in the same format.
