### ISSUE TITLE
About current patch "ignore king distance in passed pawn evaluation."

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#507]
The term "king distance" is useful in endgames but there are no endgames in Crazyouse.
So optimization is probably pointless.

**Comment by ddugovic** [comment]
@ianfab This should be an interesting discussion...

I recently created a patch 1171835ee7541404895940c812cf7e067766e184 which applies the endgame complexity term (based upon an endgame evaluation, of which "king distance" is a component) to the middlegame.

But separate from that, this added code seems like a significant speedup.

**Comment by ianfab** [comment]
@Vinvin20 That is exactly the point of my patch. Since the distance of the kings from a passed pawn (that is what I just called "king distance" there) does not matter that much in crazyhouse, I try to **skip** this part of the evaluation. Sorry, my commit messages are not always very descriptive when I quickly submit some tests, but I usually at least try to write them more clearly when opening a PR.

@ddugovic Tweaks of the initiative value similar to the recent upstream change might be promising, especially for atomic. The initiative term could be an interesting ground for further experiments, since we have not really tried to tweak this term for variants before (apart from skipping it).

**Comment by ddugovic** [comment]
My initiative patches for atomic and crazyhouse failed (or at least no longer potentially conflict/overlap with this speedup).

**Comment by Vinvin20** [comment]
The most effective speed up we can get for crazyhouse is to remove all the endgame evaluations and use only one term in final eval : change (Middlegame , Endgame ) to only (Middlegame).

**Comment by ddugovic** [comment]
What's most effective for one variant is slowest for standard chess (due to all the added code).

**Comment by ddugovic** [comment]
I created a patch 6d27f4c5629f450352021022881e31e9178f1bd0 although I'd be shocked if it had a positive effect.

**Comment by ianfab** [comment]
@ddugovic Thanks. If it fails to quickly I will maybe add a fixed number of games test to get a more accurate estimate of the Elo difference.

**Comment by Vinvin20** [comment]
>I created a patch 6d27f4c although I'd be shocked if it had a positive effect.

I agree, the speed up should come from not executing codes specific to endgame.

**Comment by ddugovic** [comment]
> > I created a patch 6d27f4c although I'd be shocked if it had a positive effect.
>
> I agree, the speed up should come from not executing codes specific to endgame.

By all means, feel free to submit patches... I just submitted this patch in case it happens to gain Elo (or happens to lose so many Elo that "not executing code" speedups can't save it).

**Comment by Vinvin20** [comment]
@ianfab 
>Just because crazyhouse does not have endgames like in standard chess does not mean that it does not have game phases at all.
Game phases was discussed here : https://github.com/ddugovic/Stockfish/issues/94#issuecomment-260540771
