### ISSUE TITLE
Variant suggestion - Knightmate

### ISSUE THREAD

**Issue by Nordlandia** [ddugovic/Stockfish#509]
Variant where Knights and Kings swap roles. 

Cutechess support Knightmate. 

Details - http://www.chessvariants.com/diffobjective.dir/knightmate.html

**Comment by ddugovic** [comment]
Variants with "fairy" pieces (such as a piece which is checked like a king and moves like a knight) are challenging to do in Stockfish.  Perhaps @ianfab 's fork has such ambitions, I don't know...

**Comment by ianfab** [comment]
As a separate fork knightmate should be feasible. However, integrating it with other variants is difficult, because even if you would have a fork supporting fairy pieces (which I plan to do in order to support Shatranj, Makruk, Amazon, etc. all in one fork and not having to create a new fork for each fairy piece variant), royal fairy pieces are yet a different story because it would require a lot of refactoring to support more than one royal piece type. To add it to this fork is even more challenging, or rather impossible.
