### ISSUE TITLE
Anti evaluation bug with MultiPV 5

### ISSUE THREAD

**Issue by ProgramFOX** [ddugovic/Stockfish#533]
This exact position: https://lichess.org/lLu0FI8A/black#75

Set "Multiple lines" to 5/5 and turn on the local analysis. Up to depth 58, Stockfish tells me that black's best move is around +2.2 (and the tablebases say draw so that evaluation looks correct). But past depth 58, it claims that white is definitely winning, which is wrong according to the tablebases.

**Comment by ianfab** [comment]
Thanks. My best guess would be that this is caused by the transposition table code https://github.com/ddugovic/Stockfish/blob/826eb798aacb4aa47c0cd2a77639713a14e7f155/src/search.cpp#L971 interfering with the endgame code https://github.com/ddugovic/Stockfish/blob/826eb798aacb4aa47c0cd2a77639713a14e7f155/src/endgame.cpp#L846-L849 causing wrong evaluations if we reach an identical position with a different side to move. When the TT is filled with enough bad evaluations, it might start to find a fake "forced" path to a winning position.

If this is the case, removing the dependency on the side to move in the RK endgame function could solve it. If so, the same would apply to KQK endgames in atomic chess. I will test it tonight.

**Comment by ianfab** [comment]
Endgame and TT code as well as TT size changes have an impact on the depth at which it starts to show mate scores, but the issue does not vanish. For reference, the commands I am using for reproducing the issue are:
```
setoption name multipv value 5
setoption name UCI_Variant value giveaway
position fen 8/4R3/8/3K4/8/8/2k5/8 b - - 8 38
go infinite
```

Interestingly, the score stays at around +2 when multipv is set to 1 or when setting up the position after Kb2.

I just found that removing the the following lines https://github.com/ddugovic/Stockfish/blob/826eb798aacb4aa47c0cd2a77639713a14e7f155/src/position.cpp#L2259-L2262 seems to solve issue, at least for the above mentioned position. However, I am not sure whether that just hides the issue by finding more drawish lines for black in the game cycle detection and postponing the occurence of the mate score.

@ddugovic Is there a certain reason why you added code to skip the game cycle detection for three variants? I do not think that this is the cause of the issue, I am just wondering what was the motivation.

**Comment by ddugovic** [comment]
@ianfab I think I was encountering errors (or assertions?) with the cuckoo algorithm.  Unfortunately I don't recall specifically what the problem was but it's very encouraging if this test can safely be removed.

**Comment by ddugovic** [comment]
I'm seeing a similar +2 evaluation with:
```
setoption name UCI_Variant value giveaway
position fen 8/4R3/8/3K4/8/8/2k5/8 b - - 0 1
go infinite
```

**Comment by ddugovic** [comment]
The latest upstream change improves search in general, however the following still reproduces this issue:

```
setoption name MultiPV value 5
setoption name UCI_Variant value giveaway
position fen 8/4R3/8/3K4/8/8/2k5/8 b - - 61 1
go infinite
```

**Comment by ddugovic** [comment]
Probably the root cause is something single-threaded... for example, `./stockfish bench giveaway 16 1 50 test2.fen` for that FEN appears to get in an infinite loop and stop printing output

**Comment by ddugovic** [comment]
The latest upstream change improves search in general, and I seemingly can no longer reproduce this issue.
