### ISSUE TITLE
Musketeer Chess Tournaments and playing engines

### ISSUE THREAD

**Issue by musketeerchess** [ddugovic/Stockfish#569]
Hi my friends 

 Let’s make things easier. 

The regular rules for humans is what was defined already = white choses among 10 pieces.

If black doesn’t agree, a default combination is chosen. 

If black agrees he choses the same piece and then it’s his turn to chose the remaining combination without white having the possibility to refuse blacks choice.

For engines the choice should be done like this: 

white makes a choice and then the black engine makes the second piece choice among the remaining 9 possibilities. 

This will for sure ease the task for programming. 

 This will ultimately apply to humans when updating the game to make the rules easier.

When making tournaments, the tournament director can force a default combination for all the tables. He gives the combination before the start of the round or before the tournament begins.

PS: 

My goal is the following:

Tournament using winboard or another UCI compatible user interface.

The tournament should involve a minimum of 6 different engines. 

Source code must be provided to avoid clones, the only participant with stockfish musketeer is @ianfab or @ddugovich

Winner 1500$
2nd 1000$
3d 500$ 

Each participant with working engine without easily identifiable bugs 200$

The methodology to gate chose the additional pieces etc should be agreed between programmers when we decide beginning of the tournament. Naturally i will be involved in this.

PRICES Payment method Paypal.

Additional 750$ for the programmer that can provide a GUI newly developed and that can use classic stockfish and musketeer stockfish.

Welcome to Musketeer Chess, the next Chess Evolution

> Le 14 déc. 2019 à 20:00, HGMuller <notifications@github.com> a écrit :
> 
> Now that the Musketeer Chess project seems to wake up from hibernation, I gave it a thought how the prelude could be handled in WinBoard. CECP already has commands to enable a non-standard dialog between engine and user: with "askuser TAG QUESTION" it can make the GUI pop up a dialog asking the QUESTION, and after the user types in the ANSWER, the command "TAG ANSWER" will be sent to the engine. The command "telluser MESSAGE" can be sued to present the user a MESSAGE that does not require a response.
> To negotiate the Musketeer piece the engine could for instance say: "askuser piece2 My piece choice is H. What is yours?", and the user could then type "A" for Archbishop in the response field, to cause "piece2 A" being send to the engine. Or if the engine plays black it could simply start with "askuser piece1 What piece do you pick?". A black engine can announce its choice for the gating file of the second piece through a "telluser" command, as no further response from the user is expected after that, and it can just await the first move of the user after announcing it.
> One snag is that Musketeer Chess would be an engine-defined variant (using Seirawan as parent, to enable gating and holdings to gate from), and that I would like the participating pieces to be known before the engine sends its "setup" command to define the piece symbols & IDs of the participating pieces, and the initial position. So that the GUI can put the selected pieces in the holdings, and won't offer the not-selected pieces as promotion choice. This is awkward, because WinBoard sends 'ping' immediately after the 'variant' command, so that it can know when the latter will not be replied to with a 'setup' (rather than the reply just being tardy). In that case it aborts the game with an error when the 'pong' reply arrives. So 'pong' would have to be delayed until after the 'setup' command, and thus until after completion of the negociation prelude.
> This would actually work in the current WinBoard implementation, but is a rather bad violation of the spirit of the ping/pong mechanism. But perhaps we should be pragmatic here, and redefine the commands for user communication as 'asynchronous'.
> 
> Another problem is that this would have to be done in a completely different way in a game between two engines. Unless the meaning of the 'askuser' command would be redefined in engine-engine mode, to not cause a popup, but send the squastion to the other engine.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

_Originally posted by @musketeerchess in https://github.com/ddugovic/Stockfish/issues/506#issuecomment-565754902_

**Comment by HGMuller** [comment]
Yesterday I made some progress in supporting game preludes (where players negociate the initial position before actual play starts) in WinBoard. In particular for human-engine games, where it is important to achieve a good degree of user-friendliness. I don't really like players having to type verbal responses to questions on what piece they select or which file they want to gated on; I want them to be able to make such choices by clicking an image of that piece, or a square on a chess board.
So WinBoard now allows engines to submit (in engine-defined variants) an arbitrary number of board positions to the GUI for display, using the already existing CECP 'setup' command, provided each of those except the last specify the parent variant as 'prelude'. Only the final 'setup' command has to specify the true parent variant, and will then be used to set up the initial position. This way the engine can present the user with a number of boards, on which the user then can click a piece of his own color to select something (e.g. the piece type itself, or the square where it was standing on). The engine can be informed of the selection clicks through the 'lift' command of the highlight protocol (and then present the user the next board).
As far as WinBoard is concerned this negociation process is invisible; the various choices or their announcement are not considered moves, and the game is supposed to have started from the position that resulted from the negociation. (E.g. this position will appear in a FEN tag of a saved PGN, and stepping through the game will never get you back into the prelude stage.)

This entire procedure is designed for human-engine play. In engine-engine play it is not useful to prompt the opponent for making a selection of a piece or square, when it is already known from the rules that he should make one. If we want the engines to conduct a similar negociation with each other, there should be an alternative method to make the GUI relay their choices to the opponent, which should not trigger emission of prelude 'setup' commands. I have not designed or implemented such a method yet, because **I strongly doubt it makes sense to have engines do this**: Engine-engine games are likely to start from book lines in order to force game diversity, and the prelude would then unavoidably be part of the book line. Rather than telling the engine how the book line forces them to 'negociate', we might as well just tell them what start position this negociation resulted in, and start the book line from there. This would liberate the engine from the obligation to be able to accept starting positions halfway the prelude (and us from designing methods to encode these in FEN).

This brings me to the position-encoding problem. WinBoard uses 'natural encoding', (meaning the FEN faithfully represents what is seen in the display), and for engine-defined variants it would not be obvious how to do it differently (unless the parent variant defines some conventions for this). From a display POV it would probably be best to present Musketeer Chess on an 8x10 board, with 0th and 9th ranks containing the gatable Musketeer pieces, and the other squares of these ranks blacked out. The natural FEN for such a position would explicitly show those ranks, e.g.

`ml******/rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR/**L*M*** w KQCkqb - 0 1`

From this the selected Musketeer pieces as well as their gating squares are automatically evident. Because WinBoard uses variant 'seirawan' as parent variant here (as it is the only variant that supports gating), it would generalize the castling field to a virginity field, and also mention virginity of other relevant pieces there. Of course one could also adopt the convention that presence of a piece on 0th or 9th rank implies virginity of the piece standing in front of it, and that they would otherwise be removed; in that case the extra file indicators in the castling field would be redundant. But with independent virginity information, the off-board pieces could be left there as a reminder of what one can promote to.

**Comment by musketeerchess** [comment]
Hi HG

Great !!

Winboard is really an awesome tool and you are "the Boss"!!

**Comment by musketeerchess** [comment]
Hi
Thanks to HGM winboard supports now a standard programmed way within it to support musketeer chess. So programmers are welcome to make their uci engines compatible with winboard and using his:

You’ll find useful informations for your engines here: http://talkchess.com/forum3/viewtopic.php?f=7&t=72572&start=10#p822789
And in following discussions.

Next online is stockfish compilation to be supported under winboard.
For anyone who wants a small gift for the new year you know what’s needed. Mail me
