### ISSUE TITLE
Consider what Game Phase means in Crazyhouse

### ISSUE THREAD

**Issue by ddugovic** [ddugovic/Stockfish#94]
Given that all Stockfish evaluations depend on game phase, it seems appropriate to define what game phase means in crazyhouse (so upstream changes are less likely to cause regression issues).

In normal chess, game phase is calculated based on material remaining on the board, so factors like king safety decrease and passed pawns increase as pieces exchange.

In crazyhouse, it's possible the opposite may be appropriate since exchanged pieces are placed back on the board with a vengenace!

@ianfab Thoughts?

**Comment by Vinvin20** [comment]
Yes, there's no endgame in crazy house, you can drop that from Stockfish.
Some ideas for Phases : 
- very early beginning -> no piece to drop, no king in danger
- King(s) is under attack (checks have to be resolved if possible)
- King(s) is very save (the engine has to find something to do others than king attack )

**Comment by ianfab** [comment]
I briefly thought about that when I implemented the rules, but I came to the conclusion that it probably is not that important for the time being, because the game phase (in the current definition) does not change as much in Crazyhouse as in other variants or standard chess.

However, of course, it makes sense to use this information. This again raises the unsolved problem of the definition of `nonPawnMaterial` for variants.

The problem is that the evaluation is sensitive to the game phase in terms like king safety, passed pawns, etc. While the king might be in more danger when we have more pieces to drop, passed pawns probably are more dangerous when there are only few pieces on the board, since we cannot capture it by dropping a piece. So they are important in the same game phase in Crazyhouse (if my reasoning is correct), whereas in standard chess they are important in different game phases.

**Comment by ddugovic** [comment]
@ianfab I agree game phase is less likely to vary; my main concern here is that upstream (official-stockfish) parameter tuning might break whatever changes we make.

I assume in terms of static evaluation, pieces in hand should count when considering game phase (and perhaps should count double!) such that exchanging pieces to "trade down to an endgame" is not a strategy to improve king safety, etc.

**Comment by ianfab** [comment]
Among others, I am currently running a test where I do not change existing king danger terms, but simply add values according to the number and type of pieces in hand. This could (over-)compensate for the gain in king safety by exchanging pieces. I think this could be a simply and effective measure. I also test a patch where I introduce general bonuses for pieces in hand to compensate for piece-square tables and mobility bonuses. By increasing the endgame bonus for pieces in hand, we could achieve a similar effect.

**Comment by sf-x** [comment]
> pieces in hand should count when considering game phase 

This means the game phase is simply constant in the absence of promoted pieces.
> such that exchanging pieces to "trade down to an endgame" is not a strategy to improve king safety

In normal chess Stockfish uses computed king safety for midgame and zero for endgame, you can simply use the same value for both "midgame" and "endgame" [here](https://github.com/ddugovic/Stockfish/blob/ed458f2bc276da62f75b0efc6b4a77f1f24ca16e/src/evaluate.cpp#L559) , or perharps higher value for "endgame" (low material on board...)

**Comment by ddugovic** [comment]
Thanks, that makes sense.

It seems at this time there is a consensus that game phase should only refer to material on the board, and that crazyhouse evaluations should apply bonuses/penalties atop the standard chess implementation (and when that standard changes, bonuses/penalties need to be retuned).

**Comment by ianfab** [comment]
It perfectly makes sense to use the same king danger score calculation for midgame and endgame. The pieces in hand can then be accounted for by the ideas I mentioned above. The tuning session for these is still running.

Just to get an idea of the Elo sensitivity of changes to the midgame/endgame definition, I tested a version where the game phase was always set to `PHASE_MIDGAME` and the result was:
ELO: 61.08 +-30.2 (95%) LOS: 100.0%
Total: 500 W: 282 L: 195 D: 23

**Comment by rpdelaney** [comment]
In chess, the rook is valued higher than the bishop or knight because rooks tend to dominate the minor pieces in the endgame. But in the middlegame, especially in crazyhouse, rooks do not dominate the bishop or knight at all. Thus, stockfish over-prices the value of the rook in crazyhouse.

**Comment by ddugovic** [comment]
@rpdelaney Why do you believe these automatically-generated and heavily tested values are incorrect?
http://github.com/ddugovic/Stockfish/blob/master/src/types.h#L280-L286

**Comment by sf-x** [comment]
> Just to get an idea of the Elo sensitivity of changes to the midgame/endgame definition, I tested a version where the game phase was always set to PHASE_MIDGAME and the result was:
ELO: 61.08 +-30.2 (95%) LOS: 100.0%
Total: 500 W: 282 L: 195 D: 23

Did this experiment go anywhere?

**Comment by ianfab** [comment]
@sf-x [This commit](https://github.com/ddugovic/Stockfish/commit/7e666f50c71525ebbc0a6c8f042d048b97261e06) deals with the value and king danger of pieces in hand. Apart from that I do not know how my test result could be used to directly derive an idea for an improvement, except for simply tuning midgame and endgame values.

**Comment by Vinvin20** [comment]
I read comments here : https://github.com/ddugovic/Stockfish/issues/112#issuecomment-258915586
It seems SF-zh doesn't develop its pieces fast enough.

**Comment by Unihedro** [comment]
Another game that is similar to crazyhouse in that it has piece dropping is probably shogi. Most shogi strategies do describe three phases:

> ## Joban (序盤)

>This is when you start and form your pieces for attack and defense. The aim of this phase is to position your pieces for better attack and stronger defense. You will also choose which opening strategy you will be using. For this, knowing Joseki (定跡=system opening moves) will help . Capturing and exchanging of the pieces will be minimal at this stage.

>## Chuuban (中盤)

>This phase is when you initiate your attack moves and exchange pieces, hopefully to your advantage. You will  try to converge where your opponent's King is. You judge the situation with the position of your pieces and also with the value of pieces you have on the board and on hand.

>## Syuuban (終盤)

>This phase is when you will try to checkmate (詰み=Tsumi) or brinkmate (必至=Hissi) your opponent's King. The value of pieces at hand is not as important. Speed to which you close in your opponent is a top priority.

(source: http://www.shogishack.net/pages/shogi-strategies/)

These strategies are vastly different from regular chess and I think it's close to the essence of crazyhouse.

When I watch players playing bughouse, it is really entertaining because in addition to identifying the phases, they also have to actively balance their team power to lead to a win even if it's only a brinkmate. Unlike bughouse though, crazyhouse only has one board and yourself to count on, so an "endgame" is merely the fact that a decisive attack closing in a king is actively happening.

**Comment by ddugovic** [comment]
> ## Syuuban (終盤)
> 
> This phase is when you will try to checkmate (詰み=Tsumi) or brinkmate (必至=Hissi) your opponent's King. The value of pieces at hand is not as important. Speed to which you close in your opponent is a top priority.

It seems to me this phase is characterized by either (or both) kings being unsafe and either (or both) players having pieces in hand, probably enough pieces to brinkmate.  Thanks to the most recent commit there are per-player counts of `ALL_PIECES` in hand...

**Comment by Vinvin20** [comment]
I had some idea about this subject : 
- Joban <- no such a phase in ZH. In Shogi that could take 4-6 moves for each player to moves pieces in their camp but in ZH after 1 or 2 moves the players has already a pawn or a piece that could take something. 

- Chuuban, in ZH, all moves but the following phase (null moves are very interesting here) ...

- Syuuban, when there are open lines around the king (sac of pawn or knight is interesting to open lines) or even sooner when there's some checks and when there are some pieces in hand to threat the king. Or "when there more than 3 checks in a row or instead of checks, mate in 2 threats". It would be interesting to have piece value tuning for this phase !

**Comment by sf-x** [comment]
Given the amount of CPU time spent on crazyhouse tuning since this issue was opened, the current definition probably can't be changed without a long re-tuning effort. Is changing definition of the game phase more likely to give an improvement that most other changes? I don't think so.

**Comment by ianfab** [comment]
I agree. Many parameter values for crazyhouse already are quite different for "middlegame" and "endgame", so it's unlikely that changing game phase does not result in a regression. Furthermore, I think the current definition proved to be quite reasonable, so I see no reason to change it.

**Comment by ddugovic** [comment]
I agree that actually implementing this change would be a very large effort, and I'm not claiming that this is a high priority.

**Comment by ianfab** [comment]
I noticed that since 74131088 non-pawn material and game phase in crazyhouse should be more or less constant, if I understand correctly. I was surprised that [reverting the changed definition seems to be a regression](http://35.161.250.236:6543/tests/view/5bdad8b56e23db7639060c4d). Perhaps it requires some re-tuning to be able to revert it without a regression.

**Comment by ddugovic** [comment]
That sounds right; I wouldn't expect `bench crazyhouse` to change much, esp. for the start position.

**Comment by ddugovic** [comment]
Having studied crazyhouse and shogi a bit more, I agree that the current game phase functionality works well.
